2014/09/12 16:53:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to find the code you requested.' in C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php:90
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionCode()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('code')
#5 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/code')
#6 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#7 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/testdrive/index.php?r=gii/model/code&id=0
HTTP_REFERER=http://localhost/testdrive/index.php?r=gii/model/index
---
2014/09/12 23:05:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'invheader'' in C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-test\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii-test\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-test\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii-test\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testdrive/gii/model/index
HTTP_REFERER=http://localhost/testdrive/gii/model/index
---
2014/09/12 23:05:30 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'invheader'' in C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-test\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii-test\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-test\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii-test\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testdrive/gii/model/index
---
2014/09/12 23:05:59 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'invheader'' in C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-test\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii-test\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-test\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii-test\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testdrive/gii/model/index
HTTP_REFERER=http://localhost/testdrive/gii/controller/index
---
2014/09/12 23:06:08 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'invheader'' in C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-test\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii-test\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-test\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii-test\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testdrive/gii/model/index
HTTP_REFERER=http://localhost/testdrive/gii/controller/index
---
2014/09/12 23:12:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "inveader/index"' in C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('inveader/index')
#1 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/inveader/index
---
2014/09/12 23:44:03 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:21)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (21)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/12 23:47:12 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:20)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (20)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/12 23:52:16 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:20)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (20)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/12 23:54:31 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:19)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (19)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/12 23:54:58 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:19)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (19)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/12 23:59:38 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:19)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (19)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/13 00:01:04 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:21)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (21)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/13 00:02:10 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:21)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (21)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/13 00:03:47 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:22)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (22)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/13 00:04:55 [error] [php] json_decode() expects parameter 1 to be string, array given (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:21)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CBaseController.php(95): InvheaderController->renderInternal()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#3 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#4 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#7 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#9 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (21)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/13 00:37:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "invheader" solicitada.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(270): CController->missingAction('invheader')
#1 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('invheader')
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/invhe...')
#3 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/invheader/index
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/13 00:37:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "invheader" solicitada.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(270): CController->missingAction('invheader')
#1 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('invheader')
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/invhe...')
#3 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/invheader/index
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 15:18:36 [error] [php] Undefined variable: inv (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:36)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (36)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 15:21:14 [error] [exception.CException] exception 'CException' with message 'Invheader y sus behaviors no tienen un método o closure llamado "all".' in C:\xampp\htdocs\yii-test\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\db\ar\CActiveRecord.php(227): CComponent->__call('all', Array)
#1 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(8): CActiveRecord->__call('all', Array)
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(8): Invheader->all()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('index')
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/index')
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/testdrive/invheader/index
---
2014/09/15 15:29:10 [error] [php] include(Cjson.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii-test\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testdrive\protected\views\invheader\index.php(36): spl_autoload_call()
#1 C:\xampp\htdocs\yii-test\framework\web\CBaseController.php(126): require()
#2 C:\xampp\htdocs\yii-test\framework\web\CBaseController.php(95): InvheaderController->renderInternal()
#3 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#5 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#6 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#7 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#9 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#10 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#11 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (36)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 16:17:37 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 16:17:55 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 16:20:18 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 16:22:27 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 16:24:50 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 16:25:11 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 16:34:35 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 16:35:16 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
---
2014/09/15 16:37:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "update" solicitada.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(270): CController->missingAction('update')
#1 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#3 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/update?data=miArray
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 16:37:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "update" solicitada.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(270): CController->missingAction('update')
#1 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#3 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 16:48:36 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 16:50:09 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 16:55:35 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 16:56:47 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
---
2014/09/15 16:57:08 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 16:58:54 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
---
2014/09/15 17:00:55 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:03:43 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:04:07 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:04:28 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:04:31 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
---
2014/09/15 17:05:35 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:12:33 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:17:35 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:19:07 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:45:37 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 17:46:14 [error] [exception.CException] exception 'CException' with message 'La propiedad "InvheaderController"."enableCsrfValidation" no se encuentra definida.' in C:\xampp\htdocs\yii-test\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(19): CComponent->__set('enableCsrfValid...', false)
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(306): InvheaderController->beforeAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('index')
#5 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/index')
#6 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#7 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/testdrive/invheader/index
---
2014/09/15 18:05:32 [error] [exception.CException] exception 'CException' with message 'La propiedad "InvheaderController"."enableCsrfValidation" no se encuentra definida.' in C:\xampp\htdocs\yii-test\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(19): CComponent->__set('enableCsrfValid...', false)
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(306): InvheaderController->beforeAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('index')
#5 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/index')
#6 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#7 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/testdrive/invheader/index
---
2014/09/15 18:07:58 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 18:09:15 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 18:15:55 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 18:17:29 [error] [php] Undefined variable: data (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:27)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (27)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 18:19:48 [error] [php] Undefined variable: data (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:27)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (27)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 18:36:25 [error] [php] Undefined variable: data (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:27)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (27)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 18:39:29 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 18:40:23 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 18:40:59 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 18:42:17 [error] [php] Undefined variable: data (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:27)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (27)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 18:46:27 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:27)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (27)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 18:50:02 [error] [php] json_decode() expects parameter 1 to be string, array given (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:26)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (26)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 18:57:08 [error] [exception.CException] exception 'CException' with message 'CHttpRequest y sus behaviors no tienen un método o closure llamado "isPostRequest".' in C:\xampp\htdocs\yii-test\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(25): CComponent->__call('isPostRequest', Array)
#1 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(25): CHttpRequest->isPostRequest()
#2 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionUpdate()
#3 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#8 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 19:01:01 [error] [exception.CException] exception 'CException' with message 'InvheaderController y sus behaviors no tienen un método o closure llamado "loadModel".' in C:\xampp\htdocs\yii-test\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(24): CComponent->__call('loadModel', Array)
#1 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(24): InvheaderController->loadModel('3')
#2 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionUpdate()
#3 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#8 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 19:06:15 [error] [php] Undefined variable: val (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (29)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 22:03:35 [error] [php] Undefined variable: val (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (29)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 22:05:49 [error] [php] Undefined variable: val (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (29)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 22:05:50 [error] [php] Undefined variable: val (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (29)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 22:05:52 [error] [php] Undefined variable: val (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (29)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 22:05:53 [error] [php] Undefined variable: val (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (29)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 22:05:54 [error] [php] Undefined variable: val (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (29)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 22:09:19 [error] [php] Undefined variable: val (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (29)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 22:12:47 [error] [php] Undefined variable: val (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (29)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 22:14:15 [error] [php] Undefined variable: val (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (29)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 22:17:40 [error] [php] Undefined variable: val (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (29)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 22:22:15 [error] [php] Undefined variable: val (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (29)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 22:25:51 [error] [php] Undefined variable: val (C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php:26)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/update
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (26)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 23:23:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "js/dataTable.js"' in C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('js/dataTable.js')
#1 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/js/dataTable.js
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:34:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "index"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/index
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/css/bootstrap-responsive.css"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/css/bootstrap-responsive.css
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/js/bootstrap-modal.js"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/js/bootstrap-modal.js
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/css/style.css"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/css/style.css
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/css/bootstrap.css"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/css/bootstrap.css
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/js/bootstrap-alert.js"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/js/bootstrap-alert.js
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/js/bootstrap-transition.js"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/js/bootstrap-transition.js
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/js/bootstrap-dropdown.js"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/js/bootstrap-dropdown.js
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/js/bootstrap-tab.js"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/js/bootstrap-tab.js
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/js/bootstrap-scrollspy.js"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/js/bootstrap-scrollspy.js
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/js/bootstrap-tooltip.js"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/js/bootstrap-tooltip.js
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/js/bootstrap-button.js"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/js/bootstrap-button.js
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/js/bootstrap-popover.js"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/js/bootstrap-popover.js
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/js/bootstrap-carousel.js"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/js/bootstrap-carousel.js
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/js/bootstrap-collapse.js"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/js/bootstrap-collapse.js
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:47:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "themes/classic/js/bootstrap-typeahead.js"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/classic/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/themes/classic/js/bootstrap-typeahead.js
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 16:49:38 [error] [php] Undefined variable: clientes (C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php:6)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php(33): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/site/index
in C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php (6)
in C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php (33)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/18 17:26:23 [error] [php] Undefined variable: clientes (C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php:6)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php(33): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/site/index
in C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php (6)
in C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php (33)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/18 17:30:19 [error] [php] Undefined variable: clientes (C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php:6)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php(33): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/site/index
in C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php (6)
in C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php (33)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/18 17:31:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "page" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('page')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/page')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/page?view=about
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/18 17:31:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "contact" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('contact')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/conta...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/contact
HTTP_REFERER=http://localhost/testdrive/invheader/page?view=about
---
2014/09/18 17:31:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "login" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('login')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/login')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/login
HTTP_REFERER=http://localhost/testdrive/invheader/contact
---
2014/09/18 17:32:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "page" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('page')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/page')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/page?view=about
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/18 17:33:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "page" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('page')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/page')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/page?view=about
---
2014/09/18 17:33:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "site" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('site')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('site')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/site/...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/site/page?view=about
---
2014/09/18 17:33:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "contact" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('contact')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/conta...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/contact
HTTP_REFERER=http://localhost/testdrive/invheader/site/page?view=about
---
2014/09/18 17:39:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "contact" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('contact')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/conta...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/contact
HTTP_REFERER=http://localhost/testdrive/invheader/contact
---
2014/09/18 17:39:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "page" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('page')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/page')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/page?view=about
HTTP_REFERER=http://localhost/testdrive/invheader/contact
---
2014/09/18 17:39:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "login" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('login')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/login')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/login
HTTP_REFERER=http://localhost/testdrive/invheader/page?view=about
---
2014/09/18 17:45:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "page" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('page')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/page')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/page?view=about
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/18 17:45:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "contact" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('contact')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/conta...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/contact
HTTP_REFERER=http://localhost/testdrive/invheader/page?view=about
---
2014/09/18 17:45:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "contact" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('contact')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/conta...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/contact
---
2014/09/18 17:45:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "site" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('site')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('site')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/site/...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/site/page/view/about
HTTP_REFERER=http://localhost/testdrive/invheader/contact
---
2014/09/18 17:46:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "site" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('site')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('site')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/site/...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/site/page/view/about
---
2014/09/18 17:46:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "site" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('site')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('site')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/site/...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/site/contact
HTTP_REFERER=http://localhost/testdrive/invheader/site/page/view/about
---
2014/09/18 17:47:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "site" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('site')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('site')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/site/...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/site/contact
HTTP_REFERER=http://localhost/testdrive/invheader/site/contact
---
2014/09/18 17:47:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "site" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('site')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('site')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/site/...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/site/contact
---
2014/09/18 17:47:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "contact" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('contact')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/conta...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/contact
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/18 17:48:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "page" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('page')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/page')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/page?view=about
HTTP_REFERER=http://localhost/testdrive/invheader
---
2014/09/18 17:48:45 [error] [exception.CException] exception 'CException' with message 'InvheaderController no ha podido encontrar la vista "contact" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:878
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('contact', Array, true)
#1 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(96): CController->render('contact', Array)
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): InvheaderController->actionContact()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/conta...')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/testdrive/invheader/contact
HTTP_REFERER=http://localhost/testdrive/invheader/page?view=about
---
2014/09/18 17:52:03 [error] [exception.CException] exception 'CException' with message 'InvheaderController no ha podido encontrar la vista "contact" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:878
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('contact', Array, true)
#1 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(114): CController->render('contact', Array)
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): InvheaderController->actionContact()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/conta...')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/testdrive/invheader/contact
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 17:53:27 [error] [exception.CException] exception 'CException' with message 'InvheaderController no ha podido encontrar la vista "contact" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:878
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('contact', Array, true)
#1 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(98): CController->render('contact', Array)
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): InvheaderController->actionContact()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/conta...')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/testdrive/invheader/contact
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/18 17:54:24 [error] [exception.CException] exception 'CException' with message 'CCaptchaValidator.action "captcha" es inválido. No se ha podido encontrar dicha acción en el controlador actual.' in C:\xampp\htdocs\yii\framework\validators\CCaptchaValidator.php:77
Stack trace:
#0 C:\xampp\htdocs\yii\framework\validators\CCaptchaValidator.php(93): CCaptchaValidator->getCaptchaAction()
#1 C:\xampp\htdocs\yii\framework\web\widgets\CActiveForm.php(510): CCaptchaValidator->clientValidateAttribute(Object(ContactForm), 'verifyCode')
#2 C:\xampp\htdocs\testdrive\protected\views\invheader\contact.php(73): CActiveForm->error(Object(ContactForm), 'verifyCode')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('contact', Array, true)
#7 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(98): CController->render('contact', Array)
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): InvheaderController->actionContact()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/conta...')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testdrive/invheader/contact
---
2014/09/18 18:00:26 [error] [php] Undefined variable: clientes (C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php:6)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php(33): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/
in C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php (6)
in C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php (33)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/18 18:20:17 [error] [php] Undefined variable: clientes (C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php:6)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php(33): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/
in C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php (6)
in C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php (33)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/18 18:21:01 [error] [php] Undefined variable: clientes (C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php:6)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php(33): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/
in C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php (6)
in C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php (33)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/18 18:21:52 [error] [php] Undefined variable: clientes (C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php:6)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php(33): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/
in C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php (6)
in C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php (33)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/18 18:22:14 [error] [php] Undefined variable: clientes (C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php:6)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php(33): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/
in C:\xampp\htdocs\testdrive\themes\classic\views\site\index.php (6)
in C:\xampp\htdocs\testdrive\protected\controllers\SiteController.php (33)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/18 21:23:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "<" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('<')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('<')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/<')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/%3C?php%20echo%20Yii::app()-%3Erequest-%3EbaseUrl;%20?%3E/invheader/index
HTTP_REFERER=http://localhost/testdrive/
---
2014/09/18 21:27:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "view" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('view')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/view')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/0
HTTP_REFERER=http://localhost/testdrive/
---
