2014/09/12 16:53:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to find the code you requested.' in C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php:90
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionCode()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('code')
#5 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/code')
#6 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#7 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/testdrive/index.php?r=gii/model/code&id=0
HTTP_REFERER=http://localhost/testdrive/index.php?r=gii/model/index
---
2014/09/12 23:05:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'invheader'' in C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-test\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii-test\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-test\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii-test\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testdrive/gii/model/index
HTTP_REFERER=http://localhost/testdrive/gii/model/index
---
2014/09/12 23:05:30 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'invheader'' in C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-test\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii-test\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-test\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii-test\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testdrive/gii/model/index
---
2014/09/12 23:05:59 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'invheader'' in C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-test\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii-test\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-test\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii-test\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testdrive/gii/model/index
HTTP_REFERER=http://localhost/testdrive/gii/controller/index
---
2014/09/12 23:06:08 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'invheader'' in C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii-test\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-test\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii-test\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-test\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii-test\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii-test\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testdrive/gii/model/index
HTTP_REFERER=http://localhost/testdrive/gii/controller/index
---
2014/09/12 23:12:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "inveader/index"' in C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('inveader/index')
#1 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testdrive/inveader/index
---
2014/09/12 23:44:03 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:21)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (21)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/12 23:47:12 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:20)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (20)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/12 23:52:16 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:20)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (20)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/12 23:54:31 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:19)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (19)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/12 23:54:58 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:19)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (19)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/12 23:59:38 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:19)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (19)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/13 00:01:04 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:21)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (21)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/13 00:02:10 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:21)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (21)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/13 00:03:47 [error] [php] Array to string conversion (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:22)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (22)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/13 00:04:55 [error] [php] json_decode() expects parameter 1 to be string, array given (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:21)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CBaseController.php(95): InvheaderController->renderInternal()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#3 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#4 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#7 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#9 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (21)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/13 00:37:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "invheader" solicitada.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(270): CController->missingAction('invheader')
#1 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('invheader')
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/invhe...')
#3 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/invheader/index
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/13 00:37:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "invheader" solicitada.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(270): CController->missingAction('invheader')
#1 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('invheader')
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/invhe...')
#3 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/invheader/index
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 15:18:36 [error] [php] Undefined variable: inv (C:\xampp\htdocs\testdrive\protected\views\invheader\index.php:36)
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (36)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 15:21:14 [error] [exception.CException] exception 'CException' with message 'Invheader y sus behaviors no tienen un método o closure llamado "all".' in C:\xampp\htdocs\yii-test\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\db\ar\CActiveRecord.php(227): CComponent->__call('all', Array)
#1 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(8): CActiveRecord->__call('all', Array)
#2 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(8): Invheader->all()
#3 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('index')
#8 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/index')
#9 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/testdrive/invheader/index
---
2014/09/15 15:29:10 [error] [php] include(Cjson.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii-test\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testdrive\protected\views\invheader\index.php(36): spl_autoload_call()
#1 C:\xampp\htdocs\yii-test\framework\web\CBaseController.php(126): require()
#2 C:\xampp\htdocs\yii-test\framework\web\CBaseController.php(95): InvheaderController->renderInternal()
#3 C:\xampp\htdocs\yii-test\framework\web\CController.php(869): InvheaderController->renderFile()
#4 C:\xampp\htdocs\yii-test\framework\web\CController.php(782): InvheaderController->renderPartial()
#5 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(9): InvheaderController->render()
#6 C:\xampp\htdocs\yii-test\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#7 C:\xampp\htdocs\yii-test\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): InvheaderController->runAction()
#9 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): InvheaderController->runActionWithFilters()
#10 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): InvheaderController->run()
#11 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\testdrive\index.php(13): CWebApplication->run()
REQUEST_URI=/testdrive/invheader/index
in C:\xampp\htdocs\testdrive\protected\views\invheader\index.php (36)
in C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php (9)
in C:\xampp\htdocs\testdrive\index.php (13)
2014/09/15 16:17:37 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 16:17:55 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 16:20:18 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 16:22:27 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 16:24:50 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 16:25:11 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 16:34:35 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 16:35:16 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
---
2014/09/15 16:37:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "update" solicitada.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(270): CController->missingAction('update')
#1 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#3 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/update?data=miArray
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 16:37:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "update" solicitada.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(270): CController->missingAction('update')
#1 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#2 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#3 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 16:48:36 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 16:50:09 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 16:55:35 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 16:56:47 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
---
2014/09/15 16:57:08 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 16:58:54 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
---
2014/09/15 17:00:55 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:03:43 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:04:07 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:04:28 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:04:31 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
---
2014/09/15 17:05:35 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:12:33 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:17:35 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:19:07 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/
---
2014/09/15 17:45:37 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii-test\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii-test\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/testdrive/invheader/update
HTTP_REFERER=http://localhost/testdrive/invheader/index
---
2014/09/15 17:46:14 [error] [exception.CException] exception 'CException' with message 'La propiedad "InvheaderController"."enableCsrfValidation" no se encuentra definida.' in C:\xampp\htdocs\yii-test\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\testdrive\protected\controllers\InvheaderController.php(19): CComponent->__set('enableCsrfValid...', false)
#1 C:\xampp\htdocs\yii-test\framework\web\CController.php(306): InvheaderController->beforeAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii-test\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 C:\xampp\htdocs\yii-test\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(282): CController->run('index')
#5 C:\xampp\htdocs\yii-test\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/index')
#6 C:\xampp\htdocs\yii-test\framework\base\CApplication.php(180): CWebApplication->processRequest()
#7 C:\xampp\htdocs\testdrive\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/testdrive/invheader/index
---
2014/09/15 17:59:10 [error] [exception.CException] exception 'CException' with message 'La propiedad "InvheaderController"."enableCsrfValidation" no se encuentra definida.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\datatable-yii\protected\controllers\InvheaderController.php(19): CComponent->__set('enableCsrfValid...', false)
#1 C:\xampp\htdocs\yii\framework\web\CController.php(306): InvheaderController->beforeAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader')
#6 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#7 C:\xampp\htdocs\yii\datatable-yii\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii/datatable-yii/invheader
---
2014/09/15 18:00:21 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'dbgrid'' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1469): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\datatable-yii\protected\controllers\InvheaderController.php(10): CActiveRecord->findAll()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): InvheaderController->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\datatable-yii\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/datatable-yii/invheader
---
2014/09/15 18:02:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "update"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('update')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\datatable-yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/datatable-yii/update
HTTP_REFERER=http://localhost/yii/datatable-yii/invheader
---
2014/09/15 18:03:45 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\yii\datatable-yii\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/yii/datatable-yii/invheader/update
HTTP_REFERER=http://localhost/yii/datatable-yii/invheader
---
2014/09/15 18:04:49 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\yii\datatable-yii\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/yii/datatable-yii/invheader/update
HTTP_REFERER=http://localhost/yii/datatable-yii/invheader
---
2014/09/15 18:05:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "update"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('update')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\datatable-yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/datatable-yii/update
HTTP_REFERER=http://localhost/yii/datatable-yii/invheader
---
2014/09/15 18:17:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "update"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('update')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/testdrive/update
HTTP_REFERER=http://localhost/yii/testdrive/invheader
---
2014/09/15 18:18:25 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\yii\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/yii/testdrive/invheader/update
HTTP_REFERER=http://localhost/yii/testdrive/invheader
---
2014/09/15 18:25:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "update"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('update')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/testdrive/update
HTTP_REFERER=http://localhost/yii/testdrive/invheader
---
2014/09/15 18:26:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "update"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('update')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/testdrive/update?YII_CSRF_TOKEN=5a463f8a4cd6410bd5ed89326018f7991194018a&data=miArray&_=1410798384492
HTTP_REFERER=http://localhost/yii/testdrive/invheader
---
2014/09/15 18:28:06 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#4 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('invheader/updat...')
#5 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\yii\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/yii/testdrive/invheader/update
HTTP_REFERER=http://localhost/yii/testdrive/invheader
---
